//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBanHangGauBong_65131773.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QuanLyBanHangGauBongEntities4 : DbContext
    {
        public QuanLyBanHangGauBongEntities4()
            : base("name=QuanLyBanHangGauBongEntities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CHITIET_DONHANG> CHITIET_DONHANG { get; set; }
        public virtual DbSet<DONHANG> DONHANGs { get; set; }
        public virtual DbSet<GIOHANG> GIOHANGs { get; set; }
        public virtual DbSet<KHACHHANG> KHACHHANGs { get; set; }
        public virtual DbSet<LOAISP> LOAISPs { get; set; }
        public virtual DbSet<NHANVIEN> NHANVIENs { get; set; }
        public virtual DbSet<QUYEN> QUYENs { get; set; }
        public virtual DbSet<SANPHAM> SANPHAMs { get; set; }
        public virtual DbSet<v_ChiTietDonHang> v_ChiTietDonHang { get; set; }
        public virtual DbSet<v_DanhSachSanPham> v_DanhSachSanPham { get; set; }
    
        public virtual int sp_DangKyKhachHang(string hoTen, string tenTK, string matKhau, string email, string sDT, string gioiTinh, string diaChi)
        {
            var hoTenParameter = hoTen != null ?
                new ObjectParameter("HoTen", hoTen) :
                new ObjectParameter("HoTen", typeof(string));
    
            var tenTKParameter = tenTK != null ?
                new ObjectParameter("TenTK", tenTK) :
                new ObjectParameter("TenTK", typeof(string));
    
            var matKhauParameter = matKhau != null ?
                new ObjectParameter("MatKhau", matKhau) :
                new ObjectParameter("MatKhau", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var sDTParameter = sDT != null ?
                new ObjectParameter("SDT", sDT) :
                new ObjectParameter("SDT", typeof(string));
    
            var gioiTinhParameter = gioiTinh != null ?
                new ObjectParameter("GioiTinh", gioiTinh) :
                new ObjectParameter("GioiTinh", typeof(string));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DangKyKhachHang", hoTenParameter, tenTKParameter, matKhauParameter, emailParameter, sDTParameter, gioiTinhParameter, diaChiParameter);
        }
    
        public virtual ObjectResult<sp_DangNhapKhachHang_Result> sp_DangNhapKhachHang(string tenTK, string matKhau)
        {
            var tenTKParameter = tenTK != null ?
                new ObjectParameter("TenTK", tenTK) :
                new ObjectParameter("TenTK", typeof(string));
    
            var matKhauParameter = matKhau != null ?
                new ObjectParameter("MatKhau", matKhau) :
                new ObjectParameter("MatKhau", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_DangNhapKhachHang_Result>("sp_DangNhapKhachHang", tenTKParameter, matKhauParameter);
        }
    
        public virtual ObjectResult<sp_DangNhapNhanVien_Result> sp_DangNhapNhanVien(string tenTK, string matKhau)
        {
            var tenTKParameter = tenTK != null ?
                new ObjectParameter("TenTK", tenTK) :
                new ObjectParameter("TenTK", typeof(string));
    
            var matKhauParameter = matKhau != null ?
                new ObjectParameter("MatKhau", matKhau) :
                new ObjectParameter("MatKhau", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_DangNhapNhanVien_Result>("sp_DangNhapNhanVien", tenTKParameter, matKhauParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_TaoDonHang(Nullable<int> maKH, string diaChiGiao, string hinhThucTT)
        {
            var maKHParameter = maKH.HasValue ?
                new ObjectParameter("MaKH", maKH) :
                new ObjectParameter("MaKH", typeof(int));
    
            var diaChiGiaoParameter = diaChiGiao != null ?
                new ObjectParameter("DiaChiGiao", diaChiGiao) :
                new ObjectParameter("DiaChiGiao", typeof(string));
    
            var hinhThucTTParameter = hinhThucTT != null ?
                new ObjectParameter("HinhThucTT", hinhThucTT) :
                new ObjectParameter("HinhThucTT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_TaoDonHang", maKHParameter, diaChiGiaoParameter, hinhThucTTParameter);
        }
    
        public virtual int sp_ThemChiTietDonHang(Nullable<int> soHD, Nullable<int> maSP, Nullable<int> soLuong)
        {
            var soHDParameter = soHD.HasValue ?
                new ObjectParameter("SoHD", soHD) :
                new ObjectParameter("SoHD", typeof(int));
    
            var maSPParameter = maSP.HasValue ?
                new ObjectParameter("MaSP", maSP) :
                new ObjectParameter("MaSP", typeof(int));
    
            var soLuongParameter = soLuong.HasValue ?
                new ObjectParameter("SoLuong", soLuong) :
                new ObjectParameter("SoLuong", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemChiTietDonHang", soHDParameter, maSPParameter, soLuongParameter);
        }
    
        public virtual ObjectResult<sp_XemGioHang_Result> sp_XemGioHang(Nullable<int> maKH)
        {
            var maKHParameter = maKH.HasValue ?
                new ObjectParameter("MaKH", maKH) :
                new ObjectParameter("MaKH", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_XemGioHang_Result>("sp_XemGioHang", maKHParameter);
        }
    }
}
