//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBanHangGauBong_65131773.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class SANPHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SANPHAM()
        {
            this.CHITIET_DONHANG = new HashSet<CHITIET_DONHANG>();
            this.GIOHANGs = new HashSet<GIOHANG>();
        }
        [DisplayName("Mã sản phẩm")]
        public int MaSP { get; set; }
        public int MaLoaiSP { get; set; }

        [DisplayName("Tên sản phẩm")]
        public string TenSP { get; set; }
        [DisplayName("Ảnh sản phẩm")]
        public string AnhSP { get; set; }
        [DisplayName("Đơn giá bán")]
        public Nullable<decimal> DonGia { get; set; }
        [DisplayName("Đơn giá nhập")]
        public Nullable<decimal> GiaNhap { get; set; }
        [DisplayName("Số lượng tồn")]
        public Nullable<int> SoLuongTon { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIET_DONHANG> CHITIET_DONHANG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GIOHANG> GIOHANGs { get; set; }
        public virtual LOAISP LOAISP { get; set; }
    }
}
