//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBanHangGauBong_65131773.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_ChiTietDonHang
    {
        public int SoHD { get; set; }
        public Nullable<System.DateTime> NgayDatHang { get; set; }
        public string TenKhachHang { get; set; }
        public string TenSP { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<decimal> DonGiaBan { get; set; }
        public Nullable<decimal> ThanhTien { get; set; }
        public Nullable<decimal> TongTien { get; set; }
    }
}
