//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBanHangGauBong_65131773.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_DanhSachSanPham
    {
        public int MaSP { get; set; }
        public string TenSP { get; set; }
        public string TenLoaiSP { get; set; }
        public string KichThuoc { get; set; }
        public Nullable<decimal> DonGia { get; set; }
        public Nullable<int> SoLuongTon { get; set; }
        public string AnhSP { get; set; }
    }
}
